version: "3.7"
services:
  app:
    container_name: ServiceEmailTrigger
    build:
      context: .
    environment:
      HOSTINGER_EMAIL: ${HOSTINGER_EMAIL}
      HOSTINGER_PASSWORD: ${HOSTINGER_PASSWORD}
      SMTP: ${SMTP}
    ports:
      - "9003:8081"
    networks:
      chelepa:
        ipv4_address: 172.19.0.5

networks:
  chelepa:
    external: true